api:
  mafra:
    url: http://211.237.50.150:7080/openapi/sample/xml/Grid_20171122000000000552_1/1/5
    secret: ${API_MAFRA_SECRET}
  weather:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    secret:  ${API_WEATHER_SECRET}
  weatherAll:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst
  weatherWeek:
    url: http://apis.data.go.kr/1360000/MidFcstInfoService/getMidLandFcst
  reverseGeo:
    url: https://naveropenapi.apigw.ntruss.com/map-reversegeocode/v2/gc
    id: ${API_REGEO_ID}
    secret: ${API_REGEO_SECRET}
