api:
  mafra:
    url: http://211.237.50.150:7080/openapi/sample/xml/Grid_20171122000000000552_1/1/5
    secret: {api.mafra.secret}

  weather:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    secret: {api.weather.secret}

