server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/garden
    username: root
    password: bookitout

  jpa:
    showSql: true
    hibernate:
      ddlAuto: create
      format-sql: true