api:
  mafra:
    url: http://211.237.50.150:7080/openapi/sample/xml/Grid_20171122000000000552_1/1/5
    secret: Wom3o6rUTrWsbJCTIyw5CZVEiXfr67Zl9u7L8d9XVbdaGqmssQdl2IjMkWSIDjZeP0JCUY%2BHi4sIrLoqqQVvrA%3D%3D

  weather:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    secret: Wom3o6rUTrWsbJCTIyw5CZVEiXfr67Zl9u7L8d9XVbdaGqmssQdl2IjMkWSIDjZeP0JCUY%2BHi4sIrLoqqQVvrA%3D%3D

