api:
  mafra:
    url: http://211.237.50.150:7080/openapi/sample/xml/Grid_20171122000000000552_1/1/5
    secret: ${API_MAFRA_SECRET}
  weather:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    secret: ${API_WEATHER_SECRET}
  reverseGeo:
    url: https://naveropenapi.apigw.ntruss.com/map-reversegeocode/v2/gc
    id:  ${API_REVERSEGEO_ID}
    secret: ${API_REVERSEGEO_SECRET}